### ISSUE TITLE
error after looking up words

### ISSUE THREAD

**Issue by fy2** [phongvcao/vim-stardict#1]
Installled with vundle, and then I ran this: 
let g:stardict_prefer_python3 = 0

(because I have Python 2.7.3)

Now when typing this, I receive:
:StarDict test
Error detected while processing function stardict#StarDict..stardict#GetDefinition:
line   15:
E121: Undefined variable: l:definition
E15: Invalid expression: l:definition

**Comment by fy2** [comment]
Also seeing this (after having vim compile with python feature:
Error detected while processing function stardict#StarDict..stardict#GetDefinition:
line   11:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'GetDefinitionInner' is not defined
line   12:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'definition' is not defined
E858: Eval did not return a valid python object

**Comment by phongvcao** [comment]
@fy2 okay I spotted this bug yesterday it was a long time since I last used Python 2 LoL. I am moving in a new apartment so I will come back to this bug in a week. Stay tuned.

**Comment by fy2** [comment]
Thanks a lot phongvcao, if you are sure that python3 will fix this, I will recompile vim with python3.

**Comment by phongvcao** [comment]
@fy2 yes it is working fine with Python 3 (I am using it now with Python 3) but if you prefer to use Vim with Python 2 then please keep using it. There is no need to change your Python preference just to get this plugin working, because Vim with Python 3 will probably mess up lots of other Python2-only plugins that you have, for example vdebug and YouCompleteMe. Even though you can compile Vim with both Python 2 and 3, from what I have read Vim can only load one of them on startup. But if vim-stardict is such important to you then you can switch but I will soon roll out a fix for Python 2 so stay tuned.

**Comment by fy2** [comment]
I will hold back the switch to Python 3 and wait for your fix for Python 2. Thanks a lot!

**Comment by phongvcao** [comment]
@fy2 I couldn't reproduce your error on my machine. I installed Vim with +python and -python3 support and included the option `let g:stardict_prefer_python3 = 0` and everything worked fine (I am using Python 2.7.10 though):

![untitled](https://cloud.githubusercontent.com/assets/874795/8051720/fd8bed82-0e34-11e5-9003-fe600de88e1b.png)

I believe you should run a `:PluginUpdate` inside your Vim and see if some new commits of mine actually fixed this issue.

If the issue was still not resolved, please include this snippet of code in your `~/.vimrc` and run `:PythonVersion` inside your Vim and give me the output.

``` VimL
" Include this in your ~/.vimrc
function! PythonVersion()
    if has("python")
        python import sys; print(sys.version)
    elseif has("python3")
        python3 import sys; print(sys.version)
    else
        echo "Your Vim was not compiled with +python (or +python3) support!"
    endif
endfunction

command! PythonVersion call PythonVersion()
```

I am thinking about removing the g:stardict_prefer_python3 option because vim-stardict should work with whatever Python version Vim was compiled with, not the version the user specifies. 

Anyway, try to update to the newest vim-stardict version and included the above snippet in your `~/.vimrc`, then run `:PythonVersion` and give me the output.

**Comment by fy2** [comment]
:PluginUpdate did the trick. No more errors! 

However, for any word I search, I receive the message: 
"Nothing similar to xyz sorry :" (where 'xyz' is a common English word, that a dictionary should have found, such as 'test').

I believe this must be related to some sort of missing external dictionaries. Not sure. I will re-read the installation instructions, maybe I am missing something.

**Comment by fy2** [comment]
Looks like I had to install the dictionaries manually for sdcv! It all works now. Thanks a lot phongvcao!

**Comment by phongvcao** [comment]
The dictionaries for sdcv must be installed into `/usr/share/stardict/dic`, which is the dictionary directory for StarDict. Have fun!
